//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> PrimaryExpression()
 * f1 -> "["
 * f2 -> ExpressionList()
 * f3 -> "]"
 */
public class ArrayAccess implements Node {
   public PrimaryExpression f0;
   public NodeToken f1;
   public ExpressionList f2;
   public NodeToken f3;

   public ArrayAccess(PrimaryExpression n0, NodeToken n1, ExpressionList n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public ArrayAccess(PrimaryExpression n0, ExpressionList n1) {
      f0 = n0;
      f1 = new NodeToken("[");
      f2 = n1;
      f3 = new NodeToken("]");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

