//
// Generated by JTB 1.2.2
//

package syntaxtree;
import set.*;
/**
 * Grammar production:
 * f0 -> Expression()
 * f1 -> "="
 * f2 -> Expression()
 * f3 -> ";"
 */
public class Assignment extends MhpStatement implements Node {
   public Expression f0;
   public NodeToken f1;
   public Expression f2;
   public NodeToken f3;
   public Assignment(Expression n0, NodeToken n1, Expression n2, NodeToken n3) {
       super();
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Assignment(Expression n0, Expression n1) {
       super();
      f0 = n0;
      f1 = new NodeToken("=");
      f2 = n1;
      f3 = new NodeToken(";");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

