//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "("
 * f1 -> "double"
 * f2 -> ")"
 * f3 -> Expression()
 */
public class CoercionToDoubleExpression implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeToken f2;
   public Expression f3;

   public CoercionToDoubleExpression(NodeToken n0, NodeToken n1, NodeToken n2, Expression n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public CoercionToDoubleExpression(Expression n0) {
      f0 = new NodeToken("(");
      f1 = new NodeToken("double");
      f2 = new NodeToken(")");
      f3 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

