//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "double"
 */
public class DoubleType implements Node {
   public NodeToken f0;

   public DoubleType(NodeToken n0) {
      f0 = n0;
   }

   public DoubleType() {
      f0 = new NodeToken("double");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

