//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "dist.factory.block"
 * f1 -> "("
 * f2 -> Expression()
 * f3 -> ")"
 */
public class FactoryBlock implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Expression f2;
   public NodeToken f3;

   public FactoryBlock(NodeToken n0, NodeToken n1, Expression n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public FactoryBlock(Expression n0) {
      f0 = new NodeToken("dist.factory.block");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = new NodeToken(")");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

