//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> ( TopLevelDeclaration() )*
 * f1 -> <EOF>
 */
public class File implements Node {
   public NodeListOptional f0;
   public NodeToken f1;

   public File(NodeListOptional n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public File(NodeListOptional n0) {
      f0 = n0;
      f1 = new NodeToken("");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

