//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "final"
 * f1 -> Type()
 * f2 -> Identifier()
 */
public class FinalFormalParameter implements Node {
   public NodeToken f0;
   public Type f1;
   public Identifier f2;

   public FinalFormalParameter(NodeToken n0, Type n1, Identifier n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public FinalFormalParameter(Type n0, Identifier n1) {
      f0 = new NodeToken("final");
      f1 = n0;
      f2 = n1;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

