//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "finish"
 * f1 -> Statement()
 */
public class FinishStatement extends MhpStatement implements Node {
   public NodeToken f0;
   public Statement f1;

   public FinishStatement(NodeToken n0, Statement n1) {
       super();
      f0 = n0;
      f1 = n1;
   }

   public FinishStatement(Statement n0) {
       super();
      f0 = new NodeToken("finish");
      f1 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

