//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> FinalFormalParameter()
 *       | UpdatableFormalParameter()
 */
public class FormalParameter implements Node {
   public NodeChoice f0;

   public FormalParameter(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

