//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "here"
 */
public class HereLiteral implements Node {
   public NodeToken f0;

   public HereLiteral(NodeToken n0) {
      f0 = n0;
   }

   public HereLiteral() {
      f0 = new NodeToken("here");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

