//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "["
 * f1 -> Identifier()
 * f2 -> ( IdentifierRest() )*
 * f3 -> "]"
 */
public class IdentifierList implements Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeListOptional f2;
   public NodeToken f3;

   public IdentifierList(NodeToken n0, Identifier n1, NodeListOptional n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public IdentifierList(Identifier n0, NodeListOptional n1) {
      f0 = new NodeToken("[");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken("]");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

