//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "new"
 * f1 -> Identifier()
 * f2 -> "("
 * f3 -> [ ExpressionList() ]
 * f4 -> ")"
 */
public class NewObject implements Node {
   public NodeToken f0;
   public Identifier f1;
   public NodeToken f2;
   public NodeOptional f3;
   public NodeToken f4;

   public NewObject(NodeToken n0, Identifier n1, NodeToken n2, NodeOptional n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public NewObject(Identifier n0, NodeOptional n1) {
      f0 = new NodeToken("new");
      f1 = n0;
      f2 = new NodeToken("(");
      f3 = n1;
      f4 = new NodeToken(")");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

