//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "place"
 */
public class PlaceType implements Node {
   public NodeToken f0;

   public PlaceType(NodeToken n0) {
      f0 = n0;
   }

   public PlaceType() {
      f0 = new NodeToken("place");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

