//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "rank"
 * f1 -> "=="
 * f2 -> IntegerLiteral()
 */
public class RankEquation implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public IntegerLiteral f2;

   public RankEquation(NodeToken n0, NodeToken n1, IntegerLiteral n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public RankEquation(IntegerLiteral n0) {
      f0 = new NodeToken("rank");
      f1 = new NodeToken("==");
      f2 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

