//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "["
 * f1 -> ColonExpression()
 * f2 -> ( ColonRest() )?
 * f3 -> "]"
 */
public class RegionConstant implements Node {
   public NodeToken f0;
   public ColonExpression f1;
   public NodeOptional f2;
   public NodeToken f3;

   public RegionConstant(NodeToken n0, ColonExpression n1, NodeOptional n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public RegionConstant(ColonExpression n0, NodeOptional n1) {
      f0 = new NodeToken("[");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken("]");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

