//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "String"
 */
public class StringType implements Node {
   public NodeToken f0;

   public StringType(NodeToken n0) {
      f0 = n0;
   }

   public StringType() {
      f0 = new NodeToken("String");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

