//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "this"
 */
public class This implements Node {
   public NodeToken f0;

   public This(NodeToken n0) {
      f0 = n0;
   }

   public This() {
      f0 = new NodeToken("this");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

