//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "-"
 * f1 -> PrimaryExpression()
 */
public class UnaryMinusExpression implements Node {
   public NodeToken f0;
   public PrimaryExpression f1;

   public UnaryMinusExpression(NodeToken n0, PrimaryExpression n1) {
      f0 = n0;
      f1 = n1;
   }

   public UnaryMinusExpression(PrimaryExpression n0) {
      f0 = new NodeToken("-");
      f1 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

