//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> Type()
 * f1 -> Identifier()
 * f2 -> "="
 * f3 -> Expression()
 * f4 -> ";"
 */
public class UpdatableVariableDeclaration implements Node {
   public Type f0;
   public Identifier f1;
   public NodeToken f2;
   public Expression f3;
   public NodeToken f4;

   public UpdatableVariableDeclaration(Type n0, Identifier n1, NodeToken n2, Expression n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public UpdatableVariableDeclaration(Type n0, Identifier n1, Expression n2) {
      f0 = n0;
      f1 = n1;
      f2 = new NodeToken("=");
      f3 = n2;
      f4 = new NodeToken(";");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

