//
// Generated by JTB 1.2.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "void"
 */
public class VoidType implements Node {
   public NodeToken f0;

   public VoidType(NodeToken n0) {
      f0 = n0;
   }

   public VoidType() {
      f0 = new NodeToken("void");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

